/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   onboarding-page.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace ApiElements {

  /**
   * `onboarding-page`
   *
   * ## Styling
   *
   * `<onboarding-page>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--onboarding-page` | Mixin applied to this elment | `{}`
   */
  class OnboardingPage extends PolymerElement {
    withImage: boolean|null|undefined;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "onboarding-page": ApiElements.OnboardingPage;
  }
}

export {};
