/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ArcOnboarding.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

export {ArcOnboarding};

/**
 * `<arc-onboarding>` Onboarding tutorial for the ARC
 *
 * ### Example
 * ```
 * <arc-onboarding></arc-onboarding>
 * ```
 *
 * ### Styling
 * `<arc-onboarding>` provides the following custom properties and mixins for styling:
 *
 * Custom property | Description | Default
 * ----------------|-------------|----------
 * `--arc-onboarding` | Mixin applied to the element | `{}`
 */
declare class ArcOnboarding extends LitElement {
  constructor();
  render(): any;
  _followLink(e: any): any;
  _closedHandler(): void;
}
