/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/OnboardingPage.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {OnboardingPage};

declare namespace ApiElements {

  /**
   * `onboarding-page`
   */
  class OnboardingPage extends LitElement {
    withImage: boolean|null|undefined;
    constructor();
    render(): any;
  }
}
