/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/OnboardingTutorial.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

import {ArcResizableMixin} from '@advanced-rest-client/arc-resizable-mixin/arc-resizable-mixin.js';

import {ArcOverlayMixin} from '@advanced-rest-client/arc-overlay-mixin/arc-overlay-mixin.js';

import {AnypointSelectableMixin} from '@anypoint-web-components/anypoint-selector/anypoint-selectable-mixin.js';

export {OnboardingTutorial};

declare namespace ApiElements {

  /**
   * `onboarding-page`
   */
  class OnboardingTutorial {
    readonly previousEnabled: Boolean|null;
    readonly lastPage: Boolean|null;
    readonly nextLabel: String|null;
    readonly showSkip: Boolean|null;
    readonly noPagination: Boolean|null;
    readonly renderPrev: Boolean|null;
    render(): any;
    _paginationTemplate(): any;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _itemsHandler(e: any): void;
    _updateSelected(): void;
    _radioHandler(e: any): void;
    next(): void;
    prev(): void;
    skip(): void;
    completeTutorial(): void;
  }
}
